#!/bin/bash
#	view-private-registry  2.3.2.184  2021-04-10T13:48:25.655943-05:00 (CDT)  https://github.com/BradleyA/Search-docker-registry-v2-script  master  uadmin  six-rpi3b.cptx86.com 2.3.1-2-gb873c33  
#	   view-private-registry view-private-registry-remote -->   new release 2.3.2  
#	view-private-registry  2.3.1.181  2021-03-17T15:40:07.362268-05:00 (CDT)  https://github.com/BradleyA/Search-docker-registry-v2-script  master  uadmin  two-rpi3b.cptx86.com v2.2-138-g3cbe13c  
#	   view-private-registry -->   change output order to latest version first #15  
#	view-private-registry  V2.1.40  2019-02-18T22:40:30.213875-06:00 (CST)  https://github.com/BradleyA/Search-docker-registry-v2-script.git  uadmin  two.cptx86.com v2.0-16-gc60205a  
#	   add License and mark file with markit 
#
### view-private-registry
#       Copyright (c) 2021 Bradley Allen
#       License is in the online DOCUMENTATION, see github
### 	View private registry v2,
#		if PERSISTENT_REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY is mounted on your system
#
#	Enter the full path to your private registry v2
PERSISTENT_REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY="/usr/local/docker-registry/docker"
#
find $PERSISTENT_REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY -print | \
	grep 'v2/repositories' | \
	grep 'current' | \
	grep -v 'link' | \
	sed -e 's/\/_manifests\/tags\//:/' | \
	sed -e 's/\/current//' | \
	sed -e 's/^.*repositories\//	/' | \
	sort -Vr > /tmp/a1
cat /tmp/a1
wc -l /tmp/a1 > /tmp/a2
echo "Number of images:	`cat /tmp/a2 | awk {'print $1'}`"
echo "Disk space used:	`du -hs $PERSISTENT_REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY`"
rm /tmp/a1 /tmp/a2
